intVal=20
floatVal=20.5
complexVal=2+3j
stringData="Bharati"
listData=[1,2,3,4,5]
tupleData=(10.20,30,40)
dictionaryData={20:'bharati',30:'madhura'}
setData={0,"bharati",20,"akshata"}
BooleanVal=True
noneData=None
print(type(intVal))
print(type(floatVal))
print(type(complexVal))
print(type(stringData))
print(type(listData))
print(type(tupleData))
print(type(dictionaryData))
print(type(setData))
print(type(BooleanVal))

